// npm run generate:seed -> seed/inventory.sql: ONE inventory item per inventory-managed catalog
// product (<id>-01), size taken from the first entry of `sizes`. It is a starting point for a fresh
// database, not a statement of real stock: edit the file (or use the admin page afterwards) to match
// what is actually on the shelves. INSERT OR IGNORE keeps it safe to run twice and never overwrites
// items added through the admin page. seed/demo.sql (hand-written) is the richer sample data set.
import {writeFile, mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {collectCatalog} from '../core/catalog/collect.mjs';
import {localized} from '../core/i18n/localized.mjs';
import {loadStoreConfig, resolveCatalogDir, projectRoot} from './store-config.mjs';

const quote = value => `'${String(value).replaceAll("'", "''")}'`;
export function seedSql(products) {
  const managed = products.filter(p => p.inventory?.managed === true);
  // The separator goes before the trailing comment, otherwise the comment would swallow it.
  const rows = managed.map((p, i) => `  (${quote(p.id + '-01')}, ${quote(p.id)}, ${quote(p.sizes?.[0] ?? '')}, 'available', 'seed')${i < managed.length - 1 ? ',' : ';'}  -- ${localized(p.name).replaceAll('\n', ' ')}`);
  return [
    '-- SEED DATA (generated by `npm run generate:seed`; do not hand-edit product names here).',
    '-- One item per inventory-managed product. Adjust quantities to reality before relying on it,',
    '-- or add the remaining items from /admin/ after seeding. Safe to re-run: existing ids are skipped.',
    rows.length ? 'INSERT OR IGNORE INTO inventory_items (id, product_id, size, status, note) VALUES' : '-- (no inventory-managed products in the catalog)',
    ...rows,
    ''
  ].join('\n');
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const {config} = await loadStoreConfig();
  const {products} = await collectCatalog(await resolveCatalogDir(config), {currency: config.currency});
  const output = path.join(projectRoot, 'seed', 'inventory.sql');
  await mkdir(path.dirname(output), {recursive: true});
  await writeFile(output, seedSql(products));
  console.log(`Wrote ${path.relative(projectRoot, output)}: ${products.filter(p => p.inventory?.managed).length} seed items (one per managed product).`);
}
